name: 'Johnny Action'
description: 'testing docker action'
author: 'Johnny'
inputs: 
  myInput:
    description: 'testing input'
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
